apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-deployment
  namespace: apdev
  labels:
    app: token
spec:
  replicas: 2
  selector:
    matchLabels:
      app: token
  template:
    metadata:
      labels:
        app: token
    spec:
      containers:
      - name: token-cnt
        image: IMAGE
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "500Mi"
            cpu: "1000m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
