apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
  namespace: apdev
  labels:
    app: employee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - name: employee-cnt
        image: IMAGE
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "500Mi"
            cpu: "1000m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MYSQL_PASSWORD
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MYSQL_PORT
        - name: MYSQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MYSQL_DBNAME